#!/usr/bin/env python3

import os
import sys
import json
import argparse

from functions import *


# parse arguments from the cli. Only for testing/advanced use. All other parameters are handled by cli_input.py
def process_args():
    parser = argparse.ArgumentParser()
    # parser.add_argument('-l', '--local-path', dest="local_path",
    #                     help="Use local files, instead of downloading from the internet (not recommended).")
    parser.add_argument("-v", "--verbose", action="store_true", dest="verbose", default=True,
                        help="Print more output")
    # parser.add_argument("-d", "--debug", action="store_true", dest="debug", default=False,
    #                     help="Debug purpose, might do nothing for final user")
    parser.add_argument("-b", "--board_name", dest="board_name", type=str, nargs=1, default=[""],
                        help="Override board name. FOR TESTING ONLY")
    return parser.parse_args()


def avs_audio(platform):
    print_status("Installing AVS")
    print_error("WARNING: AVS is VERY unstable and can cause your speakers to BLOW UP! Stay below 35% to prevent your"
                " speakers from blowing up. Headphones and HDMI audio are safe from this. If the driver crashes reboot"
                " to fix it.")

    user_input = input('Type "I Understand" in all caps to continue: ')
    while user_input != "I UNDERSTAND":
        user_input = input('Type "I Understand" in all caps to continue: ')

    if "apl" in platform:
        # Firmware, tplg, and ucm is from the chrultrabook discord.
        cpdir(f"{config_path}/audio/avs/ucm", "/usr/share/alsa/ucm2/conf.d/")
        cpdir(f"{config_path}/audio/avs/apl", "/lib/firmware/intel/avs")
        cpfile(f"{config_path}/audio/avs/snd-avs.conf", "/etc/modprobe.d/snd-avs.conf")
    else:
        print_warning("WARNING: You need a patched kernel to have working speakers on kabylake.")
        cpdir(f"{config_path}/audio/avs/ucm", "/usr/share/alsa/ucm2/conf.d/")
        cpdir(f"{config_path}/audio/avs/sklkbl", "/lib/firmware/intel/avs")
        cpfile(f"{config_path}/audio/avs/snd-avs.conf", "/etc/modprobe.d/snd-avs.conf")

    if not path_exists(f"/lib/modules/{bash('uname -r')}/kernel/sound/soc/intel/avs"):
        print_error("Looks like your kernel doesn't have the avs modules. Make sure you are on atlest 6.0 with avs "
                    "enabled. If you are on a Eupnea Project kernel, run 'manage-kernels -u --mainline' to update")


def apl_audio():
    print_status("Apollolake has two audio drivers:")
    print_status("SOF: Stable but doesn't work with headphones or mic.")
    print_status("AVS: Unstable and can cause damage to speakers but supports all audio hardware.")
    driver = input("Which driver would you like to use? [sof/avs]: ")

    if driver.lower() == "sof":
        print_status("Using sof")
        # Remove avs modprobe config if it exists
        rmfile("/etc/modprobe.d/snd-avs.conf")
        sof_audio("apl", user_id)
    if driver.lower() == "avs":
        print_status("Using avs")
        # Remove sof modprobe config if it exists
        rmfile("/etc/modprobe.d/alsa-sof.conf")
        avs_audio("apl")
    else:
        print_error(f"Invalid option: {driver}")
        exit(1)


def sof_audio(platform, username):
    print_status("Installing SOF")
    # Install required packages
    # Sof firmware needs to be reinstalled for some reason.
    install_package("sof-firmware", "firmware-sof-signed", "alsa-sof-firmware", reinstall=True)
    # linux-firmware has different names on ubuntu and debian
    with open("/etc/os-release") as f:
        if "ubuntu" in f.read():
            install_package(deb_package="linux-firmware")
        else:
            install_package("linux-firmware", "firmware-linux-free firmware-linux-nonfree", "linux-firmware")
    install_package("alsa-utils", "alsa-utils", "alsa-utils")

    # Force sof driver
    cpfile(f"{config_path}/audio/sof/alsa-sof.conf", "/etc/modprobe.d/alsa-sof.conf")

    # Ucm for glk
    if platform == "glk":
        # Some distros (arch) are starting to package ucm for sof-glkda7219max in alsa-ucm-conf
        update_system()
        install_package("alsa-ucm-conf", "alsa-ucm-conf", "alsa-ucm")
        mkdir("/usr/share/alsa/ucm2/Intel")  # directory might not exist
        rmdir("/tmp/ucm-configs")
        # if "sof-glkda7219max" not in os.listdir("/usr/share/alsa/ucm2/Intel"):
        cpdir(f"{config_path}/audio/sof/sof-glkda7219max/", "/usr/share/alsa/ucm2/Intel/sof-glkda7219max/")
        cpdir(f"{config_path}/audio/sof/sof-glkda7219max/", "/usr/share/alsa/ucm2/conf.d/sof-glkda7219ma/")
        cpdir(f"{config_path}/audio/sof/da7219/", "/usr/share/alsa/ucm2/codecs/da7219/")
        # Some glk devices use cs42l42
        cpdir(f"{config_path}/audio/sof/sof-cs42l42/", "/usr/share/alsa/ucm2/conf.d/sof-cs42l42/")
        cpdir(f"{config_path}/audio/sof/cs42l42/", "/usr/share/alsa/ucm2/codecs/cs42l42/")
        # Same thing for rt5682
        bash("git clone https://github.com/eupnea-linux/ucm-configs /tmp/ucm-configs")
        cpdir("/tmp/ucm-configs/glk/sof-glkrt5682max", "/usr/share/alsa/ucm2/conf.d/sof-glkrt5682ma")

    # Ucm for cml
    if platform == "cml":
        bash("git clone https://github.com/eupnea-linux/ucm-configs /tmp/ucm-configs")
        cpdir("/tmp/ucm-configs/cml/sof-rt5682", "/usr/share/alsa/ucm2/Intel/sof-rt5682")
        cpdir("/tmp/ucm-configs/cml/sof-rt5682", "/usr/share/alsa/ucm2/sof-rt5682")
        cpdir("/tmp/ucm-configs/cml/sof-rt5682", "/usr/share/alsa/ucm2/conf.d/sof-rt5682")


def str_audio():
    print_error("StoneyRidge is not supported.")
    exit(0)


def bsw_audio():
    print_status("Fixing braswell audio")
    cpfile(f"{config_path}/audio/sof/bsw-sof.conf", "/etc/modprobe.d/bsw-sof.conf")


def zen2_audio(username):
    print_status("Installing zen2 audio")
    update_system()
    if not bash("ps -e").__contains__("pipewire-pulse"):  # Check if pipewire is running
        print_status("PipeWire is not running, installing it")
        if Path("/usr/bin/pacman").exists():
            bash("yes | pacman -S wireplumber")  # force resolve dependencies
            bash("yes | pacman -S pipewire-pulse")  # force resolve dependencies
            # Enable + start pipewire
            bash(f"systemctl --machine={username}@.host --user --now enable pipewire.service")
            # Enable + start pipewire-pulse
            bash(f"systemctl --machine={username}@.host --user --now enable pipewire-pulse.service")
            # Enable + start wireplumber
            bash(f"systemctl --machine={username}@.host --user --now enable wireplumber.service")  # enable wireplumber

        elif path_exists("/usr/bin/apt"):
            with open("/etc/os-release", "r") as file:
                os_release = file.read().lower()
            # Remove pulseaudio and install pipewire on ubuntu 22.04 or 22.10
            # On 22.10 some DEs might still use pulseaudio
            if "ubuntu 22.10" in os_release or "ubuntu 22.04" in os_release:
                # https://ubuntuhandbook.org/index.php/2022/04/pipewire-replace-pulseaudio-ubuntu-2204/
                install_package(deb_package="pipewire pipewire-pulse")
                bash("apt-get remove -y pulseaudio-module-bluetooth")  # Remove pulseaudio bluetooth module
                install_package(deb_package="pipewire-audio-client-libraries libspa-0.2-bluetooth libspa-0.2-jack "
                                            "wireplumber pipewire-media-session-")

                # copy config files
                cpfile("/usr/share/doc/pipewire/examples/alsa.conf.d/99-pipewire-default.conf",
                       "/etc/alsa/conf.d/99-pipewire-default.conf")
                cpfile("/usr/share/doc/pipewire/examples/ld.so.conf.d/pipewire-jack-x86_64-linux-gnu.conf",
                       "/etc/ld.so.conf.d/pipewire-jack-x86_64-linux-gnu.conf")
                bash("ldconfig")  # auto-create links

                # enable wireplumber
                bash(f"systemctl --machine={username}@.host --user --now enable wireplumber.service")

            elif "debian gnu/linux 11 (bullseye)" in os_release:
                # https://trendoceans.com/install-pipewire-on-debian-11/
                bash("sudo apt-get install -y pipewire pipewire-audio-client-libraries")
                open("/etc/pipewire/media-session.d/with-pulseaudio",
                     'a').close()  # create an empty file
                cpfile("/usr/share/doc/pipewire/examples/systemd/user/pipewire-pulse.service",
                       "/etc/systemd/user/pipewire-pulse.service")
                cpfile("/usr/share/doc/pipewire/examples/systemd/user/pipewire-pulse.socket",
                       "/etc/systemd/user/pipewire-pulse.socket")

                # Reload systemd configs
                bash(f"systemctl --machine={username}@.host --user daemon-reload")
                # fully disable pulseaudio
                bash(f"systemctl --machine={username}@.host --user --now disable pulseaudio.service pulseaudio.socket")
                bash(f"systemctl --machine={username}@.host --user mask pulseaudio")
                # enable pipewire
                bash(f"systemctl --machine={username}@.host --user --now enable pipewire pipewire-pulse")
        else:
            print_error(f"Something went wrong => open a github issue or create a post on the discord\nError: Distro "
                        f"not recognized (zen2 audio)")
            exit(1)
    else:
        print_status("PipeWire is already configured")

    # remove old files
    rmdir("/usr/share/alsa/ucm2/AMD/acp3xalc5682m98/")
    rmdir("/usr/share/alsa/ucm2/conf.d/acp3xalc5682m98")

    # clone repo
    bash("git clone --depth=1 https://github.com/alsa-project/alsa-ucm-conf/ /tmp/eupnea-audio")

    # Make directories
    mkdir("/usr/share/alsa/ucm2/AMD/acp3xalc5682m98/", create_parents=True)
    mkdir("/usr/share/alsa/ucm2/conf.d/acp3xalc5682m98", create_parents=True)

    # copy ucm configs
    cpfile("/tmp/eupnea-audio/ucm2/AMD/acp3xalc5682m98/HiFi.conf",
           "/usr/share/alsa/ucm2/AMD/acp3xalc5682m98/HiFi.conf")
    cpfile("/tmp/eupnea-audio/ucm2/AMD/acp3xalc5682m98/acp3xalc5682m98.conf",
           "/usr/share/alsa/ucm2/AMD/acp3xalc5682m98/acp3xalc5682m98.conf")
    bash("cd /usr/share/alsa/ucm2/conf.d/acp3xalc5682m98 ; ln ../../AMD/acp3xalc5682m98/acp3xalc5682m98.conf")

    # speaker warning
    print_status("After rebooting you will need to set speakers as the output device in sound settings.")


def install_package(arch_package: str = "", deb_package: str = "", rpm_package: str = "", reinstall: bool = False):
    if Path("/usr/bin/pacman").exists():
        if reinstall:
            bash(f"pacman -S --noconfirm {arch_package}")
        else:
            bash(f"pacman -S --noconfirm --needed {arch_package}")
    elif Path("/usr/bin/apt").exists():
        if reinstall:
            bash(f"apt-get install -y --reinstall {deb_package}")
        else:
            bash(f"apt-get install -y {deb_package}")
    elif Path("/usr/bin/dnf").exists():
        if reinstall:
            bash(f"dnf reinstall -y {rpm_package}")
        else:
            bash(f"dnf install -y {rpm_package}")
    else:
        print_error(f"Unknown package manager! Please install {deb_package} using your package manager.")
        exit(1)


def remove_package(arch_package: str = "", deb_package: str = "", rpm_package: str = ""):
    if Path("/usr/bin/pacman").exists():
        bash(f"pacman -Rsn --noconfirm {arch_package}")
    elif Path("/usr/bin/apt").exists():
        bash(f"apt-get remove -y {deb_package}")
    elif Path("/usr/bin/dnf").exists():
        bash(f"dnf remove -y {rpm_package}")
    else:
        print_error(f"Unknown package manager! Please remove {deb_package} using your package manager.")
        exit(1)


def update_system() -> None:
    if Path("/usr/bin/pacman").exists():
        bash(f"pacman -Syu")
    elif Path("/usr/bin/apt").exists():
        bash(f"apt-get update")
        bash(f"apt-get -y upgrade")
    elif Path("/usr/bin/dnf").exists():
        bash(f"dnf upgrade -y")
    else:
        print_warning("Unknown package manager! Cannot update system. Skipping")
        pass


if __name__ == "__main__":
    if os.geteuid() == 0 and not path_exists("/tmp/username"):
        print_error("Please start the script as non-root/without sudo")
        exit(1)

    args = process_args()  # process args before elevating to root for better ux

    # Restart script as root
    if not os.geteuid() == 0:
        # save username
        with open("/tmp/username", "w") as file:
            # get non root username. os.getlogin() seems to fail in chroots
            file.write(bash("whoami").strip())

        # restart script as root
        sudo_args = ['sudo', sys.executable] + sys.argv + [os.environ]
        os.execlpe('sudo', *sudo_args)

    # read username
    with open("/tmp/username", "r") as file:
        user_id = file.read()

    if args.verbose:
        print_warning("Verbosity increased")
        set_verbose(args.verbose)

    # Remove old files
    rmdir("/tmp/eupnea-audio")
    mkdir("/tmp/eupnea-audio")

    # Important message
    print_warning("WARNING: this audio script is not fully functional yet!")

    # Determine if running from a git clone or a eupnea system
    if sys.argv[0] == "/usr/local/bin/setup-audio":
        config_path = "/etc/eupnea"
    else:
        config_path = "configs"

    if args.board_name[0] == "":
        # Get the board name from dmi
        with open("/sys/devices/virtual/dmi/id/product_name", "r") as dmi:
            device_board = dmi.read().lower().strip()
    else:  # use the board name from the args, for testing only
        device_board = str(args.board_name[0]).lower().strip()
        print_warning(f"Board name overriden to: {device_board}")

    with open(f"{config_path}/audio/board-generations.json", "r") as file:
        boards = json.load(file)

    try:
        match boards[device_board]:
            case "bsw":
                bsw_audio()
            case "skl":
                avs_audio("skl")
            case "kbl":
                avs_audio("skl")
            case "apl":
                apl_audio()
            case "glk":
                sof_audio("glk", user_id)
            case "whl":
                sof_audio("whl", user_id)
            case "cml":
                sof_audio("cml", user_id)
            case "jsl":
                sof_audio("jsl", user_id)
            case "tgl":
                sof_audio("tgl", user_id)
            case "str":
                str_audio()
            case "zen2":
                zen2_audio(user_id)
            case _:
                print_error(f"Unknown/Unsupported chromebook model: {device_board}")
                exit(1)
    except KeyError:
        print_error(f"Unknown/Unsupported chromebook model: {device_board}")
        exit(1)

    print_header("Audio installed successfully! Reboot to enable audio.")
    input("\033[92m" + "Press ENTER to reboot or CTRL+C to cancel reboot" + "\033[0m")
    bash("reboot")
    sleep(5)
